INSERT INTO LIVROS (NOME_LIVRO, AUTOR, ISBN, VALOR, ID_VENDEDOR) VALUES ('Nove desconhecidos', 'Liane Moriart', 123435, 19.9, 1)
INSERT INTO LIVROS (NOME_LIVRO, AUTOR, ISBN, VALOR, ID_VENDEDOR) VALUES ('Verity', 'Colleen Hoover', 65372, 34.80, 1)
INSERT INTO COMPRA (ID_COMPRADOR, ID_VENDEDOR, ID_LIVRO, VALOR, STATUS) VALUES (1, 1, 1, 12.43, 3)